server:
  port: 4002

spring:
  application:
    name: microservice-admin
  boot:
    admin:
      client:
        url: http://localhost:4002

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:4000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
