/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class acme_me_j2se_jni_JNITest */

#ifndef _Included_acme_me_j2se_jni_JNITest
#define _Included_acme_me_j2se_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     acme_me_j2se_jni_JNITest
 * Method:    plus
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_acme_me_j2se_jni_JNITest_plus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     acme_me_j2se_jni_JNITest
 * Method:    minus
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_acme_me_j2se_jni_JNITest_minus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     acme_me_j2se_jni_JNITest
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_acme_me_j2se_jni_JNITest_print
  (JNIEnv *, jobject, jstring);

/*
 * Class:     acme_me_j2se_jni_JNITest
 * Method:    get
 * Signature: (Lacme/me/j2se/serialize/Student;)Lacme/me/j2se/serialize/Student;
 */
JNIEXPORT jobject JNICALL Java_acme_me_j2se_jni_JNITest_get
  (JNIEnv *, jobject, jobject);

/*
 * Class:     acme_me_j2se_jni_JNITest
 * Method:    exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_acme_me_j2se_jni_JNITest_exit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
