server:
  port: 8081

spring:
  application:
    name: spring-cloud-provider-sso
  messages:
    basename: i18n/messages
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  devtools:
    restart:
      exclude: static/**,public/**,templates/**
      classic_compatible: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100