server:
  port: 4001

spring:
  application:
    name: spring-cloud-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        #git:
        #  uri: file://D:/git_repository/config-repo/
        #  force-pull: true
        #  searchPaths: '{application}'