sso:
  security:
    rsa_key_size: 2048
  cookie:
    domain: acme.org
    key:
      token: token
      tokenAge: 30
  param:
    default_redirct_url: http://jd.com
    key:
      redirect_url: redirect_url
      rsa_private: rsa_public_key
      pwd_salt: pwd_salt
  session:
    key:
      redirect_url: redirect_url

data:
  redis:
    standalone:
      host: 192.168.100.200
      port: 6379
  jdbc:
    standalone:
      driverClass: com.mysql.jdbc.Driver
      jdbcUrl: "jdbc:mysql://192.168.100.200:3306/test"
      username: root
      password: root
      maxActive: 50
      maxIdle: 10
      maxWait: 2000

account:
  password_hint: 密码长度在6~16位之间，必须包含数字、大小写字母和特殊字符
  password_reg: (?=^.*[a-z]+.*$)(?=^.*[A-Z]+.*$)(?=.*[0-9]+.*)(?=^.*[\`\~\!\@\#\$\%\^\&\*\(\)\_\+\-\=\{\}\|\[\]\:\;\'\<\>\?\,\.]+.*$)^.{6,16}$