server:
  port: 4000

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: microservice-eureka

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:4000/eureka
    healthcheck:
      enabled: true